### ISSUE TITLE
Adding docker-file for Container level application deployment 

### ISSUE THREAD

**Issue by arpitx165** [arpitx165/Flask-Restful-API#2]

**Comment by zorexsalvo** [comment]
Hi @arpitx165, is there already someone who is working on this issue?

**Comment by arpitx165** [comment]
Hi @zorexsalvo  no one is working on this.You can start working :)

**Comment by arpitx165** [comment]
@zorexsalvo  Thanks :)

**Comment by zorexsalvo** [comment]
@arpitx165 No prob!
